/**
 * API layer.
 *
 * All engine output reaches the app through here. Two things matter:
 *   1. The base URL is derived from the Expo dev host, so the app works on a
 *      physical device without editing an IP by hand.
 *   2. Every call has an offline fallback backed by a real engine snapshot
 *      (generated by `npm run snapshot` in the server), so a demo never shows a
 *      blank screen because a laptop went to sleep.
 */
import Constants from 'expo-constants';

import type {
  ActivitySlot,
  CascadeResult,
  Disruption,
  DisruptionType,
  GroupConstraints,
  HistoryEvent,
  NodeImpact,
  NodeKind,
  Place,
  Preferences,
  Priority,
  RankingWeights,
  RecoveryPlan,
  ResilienceScore,
  RiskPoint,
  RiskSignal,
  SafetyConstraints,
  SeasonalRisk,
  StayOption,
  TransportOption,
  Trip,
  TripEdge,
  TripNode,
  TripStatus,
} from '@/types/domain';
import offline from '@/data/offline.json';

/* ------------------------------------------------------------------ */
/* Base URL discovery                                                 */
/* ------------------------------------------------------------------ */

const PORT = 4000;

function inferBaseUrl(): string {
  const configured = (Constants.expoConfig?.extra as { apiUrl?: string } | undefined)?.apiUrl;
  // The dev server host is the machine running the API too, in every normal setup.
  const hostUri = Constants.expoConfig?.hostUri ?? (Constants as any).expoGoConfig?.debuggerHost;
  if (hostUri) {
    const host = String(hostUri).split(':')[0];
    if (host && host !== 'localhost') return `http://${host}:${PORT}`;
  }
  return configured ?? `http://localhost:${PORT}`;
}

export const API_BASE = inferBaseUrl();

export type ConnectionState = 'UNKNOWN' | 'LIVE' | 'OFFLINE';

let connection: ConnectionState = 'UNKNOWN';
const listeners = new Set<(state: ConnectionState) => void>();

export function onConnectionChange(fn: (state: ConnectionState) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

function setConnection(next: ConnectionState) {
  if (connection === next) return;
  connection = next;
  listeners.forEach((fn) => fn(next));
}

export function connectionState(): ConnectionState {
  return connection;
}

/* ------------------------------------------------------------------ */
/* Response shapes                                                    */
/* ------------------------------------------------------------------ */

export interface TripOverview {
  trip: Trip;
  headline: string;
  subhead: string;
  status: TripStatus;
  disruption: Disruption | null;
  selectedPlanId: string | null;
  hasPlans: boolean;
  weights: RankingWeights;
}

export interface ImportResponse extends TripOverview {
  stages: { key: string; label: string; detail: string; weight: number }[];
  recognised: { kind: string; title: string; confidence: number }[];
  parseSummary: string;
}

export interface GraphResponse {
  nodes: {
    id: string;
    kind: NodeKind;
    title: string;
    subtitle?: string;
    status: TripNode['status'];
    start: string;
    end: string;
    day: number;
    place?: Place;
    priority: Priority;
    cost: number;
    durationMinutes: number;
    backups: number;
  }[];
  edges: TripEdge[];
}

export interface RisksResponse {
  risks: RiskPoint[];
  resilience: ResilienceScore;
  highCount: number;
}

export interface SignalsResponse {
  signals: RiskSignal[];
  connected: number;
  seasonal: SeasonalRisk[];
  pending: Disruption | null;
}

export interface CascadeResponse {
  cascade: CascadeResult;
  narrative: string;
}

export interface PlansResponse {
  plans: RecoveryPlan[];
  recommendation: string;
  weights: RankingWeights;
  baselineNodes: TripNode[];
}

export interface AlternativesResponse {
  transport: (TransportOption & {
    replaces: string;
    durationMinutes: number;
    priceDelta: number;
    refundImpact: string;
    available: boolean;
    availability: string;
  })[];
  stays: (StayOption & {
    replaces: string;
    priceDelta: number;
    available: boolean;
    availability: string;
    refundImpact: string;
  })[];
  slots: (ActivitySlot & { title: string; current: boolean; available: boolean; availability: string })[];
  party: number;
}

export interface ScenarioResponse {
  scenario: { id: string; label: string; detail: string; disruption: Disruption };
  cascade: CascadeResult;
  narrative: string;
  ripple: { nodeId: string; title: string; status: string; hops: number; reason: string }[];
  recoverable: boolean;
  planCount: number;
  bestPlanSummary: string | null;
}

export interface CatalogueResponse {
  catalogue: Disruption[];
  quickActions: { id: string; label: string; prompt: string; kinds: NodeKind[]; types: DisruptionType[] }[];
  nodes: { id: string; kind: NodeKind; title: string; subtitle?: string }[];
}

export interface AssistantResponse {
  intent: {
    preferences: Partial<Preferences>;
    safety: Partial<SafetyConstraints>;
    priorities: { nodeId: string; priority: Priority }[];
    readings: { label: string; value: string }[];
    reply: string;
    source: 'RULES' | 'LLM';
  };
  applied: boolean;
  planCount: number;
  recommendation: string | null;
  trip: TripOverview;
}

/* ------------------------------------------------------------------ */
/* Offline snapshot adapters                                          */
/* ------------------------------------------------------------------ */

const snap = offline as any;

function offlineOverview(disrupted: boolean): TripOverview {
  const trip = (disrupted ? snap.disruptedTrip : snap.trip) as Trip;
  const broken = trip.nodes.filter((n) => n.status === 'MISSED' || n.status === 'CANCELLED').length;
  return {
    trip,
    headline: disrupted ? `${broken} bookings broken, 0 at risk` : 'Trip is on track',
    subhead: `1 Jun – 5 Jun · ${trip.travellers.length} travellers`,
    status: disrupted ? 'DISRUPTED' : 'ON_TRACK',
    disruption: disrupted ? (snap.disruption as Disruption) : null,
    selectedPlanId: null,
    hasPlans: disrupted,
    weights: snap.weights as RankingWeights,
  };
}

/** Mirrors the server's history feed closely enough to render the timeline. */
function offlineHistory(): HistoryEvent[] {
  const base = Date.parse(snap.disruption.detectedAt);
  const mk = (offsetMin: number, kind: HistoryEvent['kind'], title: string, detail: string, chain: string[]) => ({
    id: `off-${kind}-${offsetMin}`,
    tripId: snap.trip.id,
    at: new Date(base + offsetMin * 60_000).toISOString(),
    kind,
    title,
    detail,
    chain,
  });
  const impacted = (snap.cascade as CascadeResult).impacts.filter((i) => i.status !== 'SAFE');
  return [
    mk(3, 'REBUILD', 'Trip rebuilt', 'Itinerary regenerated from the accepted plan.', []),
    mk(2, 'RECOMMENDATION', `${snap.plans[0].title} recommended`, snap.recommendation, snap.plans[0].bullets),
    mk(
      2,
      'GENERATION',
      `${snap.plans.length} recovery plans generated`,
      `${snap.candidateCount} candidates passed feasibility; ${snap.shortlistCount} are genuine trade-offs.`,
      snap.plans.map((p: RecoveryPlan) => p.title),
    ),
    mk(1, 'CASCADE', 'Cascade calculated', snap.cascade.summary, impacted.map((i) => `${i.title} — ${i.status}`)),
    mk(0, 'DETECTION', snap.disruption.headline, snap.disruption.detail, [snap.disruption.headline]),
    mk(-40, 'RISK', `${snap.risks.length} risk points identified`, 'Analysed on import.', snap.risks.slice(0, 4).map((r: RiskPoint) => r.title)),
    mk(-41, 'IMPORT', 'Trip imported', snap.parse.summary, []),
  ];
}

/* ------------------------------------------------------------------ */
/* Fetch with fallback                                                */
/* ------------------------------------------------------------------ */

const TIMEOUT_MS = 6000;

async function request<T>(path: string, init: RequestInit | undefined, fallback: () => T): Promise<T> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const response = await fetch(`${API_BASE}${path}`, {
      ...init,
      signal: controller.signal,
      headers: { 'Content-Type': 'application/json', ...(init?.headers ?? {}) },
    });
    if (!response.ok) {
      const body = await response.text();
      throw new Error(`${response.status}: ${body.slice(0, 200)}`);
    }
    setConnection('LIVE');
    return (await response.json()) as T;
  } catch (error) {
    setConnection('OFFLINE');
    if (__DEV__) console.warn(`[api] ${path} → offline snapshot (${(error as Error).message})`);
    return fallback();
  } finally {
    clearTimeout(timer);
  }
}

const post = (body: unknown): RequestInit => ({ method: 'POST', body: JSON.stringify(body) });

/* ------------------------------------------------------------------ */
/* Endpoints                                                          */
/* ------------------------------------------------------------------ */

export const api = {
  health: () =>
    request<{ ok: boolean; languageModel: string }>('/api/health', undefined, () => ({
      ok: false,
      languageModel: 'offline snapshot',
    })),

  importTrip: (source: string, fileName?: string) =>
    request<ImportResponse>('/api/trips/import', post({ source, fileName }), () => ({
      ...offlineOverview(false),
      stages: snap.parse.stages,
      recognised: snap.parse.recognised,
      parseSummary: snap.parse.summary,
    })),

  trip: (id: string) => request<TripOverview>(`/api/trips/${id}`, undefined, () => offlineOverview(false)),

  reset: (id: string) =>
    request<TripOverview>(`/api/trips/${id}/reset`, post({}), () => offlineOverview(false)),

  graph: (id: string) =>
    request<GraphResponse>(`/api/trips/${id}/graph`, undefined, () => ({
      nodes: (snap.trip.nodes as TripNode[]).map((n) => ({
        id: n.id,
        kind: n.kind,
        title: n.title,
        subtitle: n.subtitle,
        status: n.status,
        start: n.start,
        end: n.end,
        day: n.day,
        place: n.location ?? n.to ?? n.from,
        priority: n.priority,
        cost: n.cost,
        durationMinutes: Math.round((Date.parse(n.end) - Date.parse(n.start)) / 60000),
        backups: 1,
      })),
      edges: snap.trip.edges as TripEdge[],
    })),

  risks: (id: string) =>
    request<RisksResponse>(`/api/trips/${id}/risks`, undefined, () => ({
      risks: snap.risks,
      resilience: snap.resilience,
      highCount: (snap.risks as RiskPoint[]).filter((r) => r.severity === 'HIGH').length,
    })),

  signals: (id: string) =>
    request<SignalsResponse>(`/api/trips/${id}/signals`, undefined, () => ({
      signals: snap.signals,
      connected: (snap.signals as RiskSignal[]).filter((s) => s.relatedNodeIds.length > 0).length,
      seasonal: snap.seasonal,
      pending: snap.disruption,
    })),

  seasonal: (id: string) =>
    request<{ relevant: SeasonalRisk[]; other: SeasonalRisk[] }>(
      `/api/trips/${id}/seasonal`,
      undefined,
      () => ({
        relevant: (snap.seasonal as SeasonalRisk[]).filter((s) => ['Dubai', 'Paris', 'Mumbai'].includes(s.city)),
        other: (snap.seasonal as SeasonalRisk[]).filter((s) => !['Dubai', 'Paris', 'Mumbai'].includes(s.city)),
      }),
    ),

  catalogue: (id: string) =>
    request<CatalogueResponse>(`/api/trips/${id}/disruptions/catalogue`, undefined, () => ({
      catalogue: snap.catalogue,
      quickActions: snap.quickActions,
      nodes: (snap.trip.nodes as TripNode[]).map((n) => ({
        id: n.id,
        kind: n.kind,
        title: n.title,
        subtitle: n.subtitle,
      })),
    })),

  applyDisruption: (id: string, disruption: Partial<Disruption>) =>
    request<TripOverview & CascadeResponse>(`/api/trips/${id}/disruptions`, post(disruption), () => ({
      ...offlineOverview(true),
      cascade: snap.cascade,
      narrative: snap.cascadeNarrative,
    })),

  cascade: (id: string) =>
    request<CascadeResponse>(`/api/trips/${id}/cascade`, undefined, () => ({
      cascade: snap.cascade,
      narrative: snap.cascadeNarrative,
    })),

  impact: (id: string, nodeId: string) =>
    request<{ nodeId: string; explanation: string; impact: NodeImpact | null }>(
      `/api/trips/${id}/cascade/${nodeId}`,
      undefined,
      () => {
        const impact = (snap.cascade as CascadeResult).impacts.find((i) => i.nodeId === nodeId) ?? null;
        return { nodeId, explanation: impact?.reason ?? 'Not connected to this disruption.', impact };
      },
    ),

  plans: (id: string) =>
    request<PlansResponse>(`/api/trips/${id}/recovery-plans`, undefined, () => ({
      plans: snap.plans,
      recommendation: snap.recommendation,
      weights: snap.weights,
      baselineNodes: snap.trip.nodes,
    })),

  selectPlan: (id: string, planId: string) =>
    request<TripOverview & { plan: RecoveryPlan; baselineNodes: TripNode[] }>(
      `/api/trips/${id}/recovery-plans/${planId}/select`,
      post({}),
      () => {
        const plan = ((snap.plans as RecoveryPlan[]).find((p) => p.id === planId) ??
          snap.plans[0]) as RecoveryPlan;
        const nodes: TripNode[] = plan.nodes.map((n) => ({ ...n, status: 'SAFE' as const }));
        return {
          trip: { ...(snap.trip as Trip), nodes, status: 'RECOVERED', recoveredFromPlanId: plan.id },
          headline: `Trip recovered — ${plan.metrics.experiencesPreserved} of ${plan.metrics.experiencesTotal} experiences saved`,
          subhead: `1 Jun – 5 Jun · ${snap.trip.travellers.length} travellers`,
          status: 'RECOVERED' as TripStatus,
          disruption: snap.disruption,
          selectedPlanId: plan.id,
          hasPlans: true,
          weights: snap.weights,
          plan,
          baselineNodes: snap.trip.nodes,
        };
      },
    ),

  alternatives: (id: string) =>
    request<AlternativesResponse>(`/api/trips/${id}/alternatives`, undefined, () => ({
      transport: [],
      stays: [],
      slots: [],
      party: snap.trip.travellers.length,
    })),

  scenarios: (id: string) =>
    request<{ scenarios: { id: string; label: string; detail: string; disruption: Disruption }[] }>(
      `/api/trips/${id}/scenarios`,
      undefined,
      () => ({ scenarios: (snap.scenarios as ScenarioResponse[]).map((s) => s.scenario) }),
    ),

  simulate: (id: string, body: { scenarioId?: string; nodeId?: string; type?: string; delayMinutes?: number }) =>
    request<ScenarioResponse>(`/api/trips/${id}/scenarios`, post(body), () => {
      const found = (snap.scenarios as ScenarioResponse[]).find((s) => s.scenario.id === body.scenarioId);
      return found ?? (snap.scenarios as ScenarioResponse[])[0];
    }),

  history: (id: string) =>
    request<{ events: HistoryEvent[] }>(`/api/trips/${id}/history`, undefined, () => ({
      events: offlineHistory(),
    })),

  savePreferences: (
    id: string,
    body: {
      preferences?: Partial<Preferences>;
      safety?: Partial<SafetyConstraints>;
      group?: Partial<GroupConstraints>;
      priorities?: { nodeId: string; priority: Priority }[];
    },
  ) => request<TripOverview>(`/api/trips/${id}/preferences`, post(body), () => offlineOverview(false)),

  savePriorities: (id: string, priorities: { nodeId: string; priority: Priority }[]) =>
    request<TripOverview>(`/api/trips/${id}/priorities`, post({ priorities }), () => offlineOverview(false)),

  assistant: (id: string, text: string) =>
    request<AssistantResponse>(`/api/trips/${id}/assistant`, post({ text }), () => ({
      intent: {
        preferences: {},
        safety: {},
        priorities: [],
        readings: [],
        reply: 'The engine is unreachable, so I cannot re-rank plans right now.',
        source: 'RULES' as const,
      },
      applied: false,
      planCount: snap.plans.length,
      recommendation: snap.recommendation,
      trip: offlineOverview(true),
    })),
};

export { offline as offlineSnapshot };
